export const CHANGE_PICKUP = "CHANGE_PICKUP";
export const CHANGE_ORIGIN_VALUE = "CHANGE_ORIGIN_VALUE";
export const UPDATE_REGION = "UPDATE_REGION";
export const CHANGE_DESTINATION_VALUE = "CHANGE_DESTINATION_VALUE";
export const CHANGE_EDIT_LOCATION = "CHANGE_EDIT_LOCATION";